#####################################
#
#            CatPawServer
#     Hanbings 3219065882@qq.com
#           (C) NanoKylin
#
#####################################
language: zh_CN

#####################################
#
#          ThreadPoolService
#           线程池管理器部分
#       corePoolSize 核心线程数
#      maximumPoolSize 最大线程数
#      keepAliveTime 存活时间 (s)
#           queue 任务缓存器
#
#####################################
corePoolSize: 6
maximumPoolSize: 50
keepAliveTime: 60
queue: 10

#####################################
#
#          WebSocketService
#          WebSocket服务部分
#              ip是IP地址
#      port是WebSocket的监听端口
#
#####################################
ip: '0.0.0.0'
port: 10086

#####################################
#
#          DataBaseService
#           数据库账户密码
#    这部分很重要 所以要保护好这个文件
#       后面会想办法加密这里的啦
#      databaseType是数据库类型
#        可选 mysql | sqlite
#    mysql需要填入URL连接 账户密码等
#    username是用户名 sqlite无需填写
#    password是密码 sqlite无需填写
#
#####################################

databaseType: 'sqlite'
mysqlURL: 'mysql type into'
username: 'mysql type into'
password: 'mysql type into'