#####################################
#            CatPawServer
#     Hanbings 3219065882@qq.com
#           (C) NanoKylin
#####################################
language: zh_CN

#####################################
#          ThreadPoolService
#           线程池管理器部分
#       corePoolSize 核心线程数
#      maximumPoolSize 最大线程数
#      keepAliveTime 存活时间 (s)
#           queue 任务缓存器
#    threadNameFormat 线程名字格式
#####################################
corePoolSize: 6
maximumPoolSize: 50
keepAliveTime: 60
queue: 10