#############################################

                Cat Paw Server
          @Hanbings 3219065882@qq.com

#############################################

#############################################
# 选择语言 一般设为./language下的文件名（不包括.yml后缀）
# 自带语言 zh_CN | en_US
#############################################
language: zh_cn

#############################################
# corePoolSize 为线程池的基本大小
# maximumPoolSize 为线程池最大线程大小
# 如果不了解CatPawServer的线程分配规则
# 请向他人咨询此参数修改方式
#############################################
corePoolSize: 5
maximumPoolSize: 50

