#####################################
#            CatPawServer
#     Hanbings 3219065882@qq.com
#           (C) NanoKylin
#####################################
language: zh_CN

#####################################
#          ThreadPoolService
#           线程池管理器部分
#     maximumPoolSize 最大线程数
#####################################
maximumPoolSize: 50
