#############################################

                Cat Paw Server
          @Hanbings 3219065882@qq.com
#############################################

# 选择语言 一般设为./language下的文件名 （不包括.yml后缀）
# 自带语言 zh_CN | en_US
language: zh_cn